package DAO;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

// Lớp trừu tượng cha dùng chung cho các DAO khác (AccountDAOImpl, UserDAOImpl, ...)
public abstract class BaseDAO {

    // Tạo đối tượng Statement từ kết nối đến database (thường dùng cho câu lệnh không có tham số ?)
    public Statement createStatement() throws SQLException {
        return DBHelper.getConnection().createStatement();
    }

    // Tạo PreparedStatement từ một câu SQL có sử dụng tham số (dấu ?)
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return DBHelper.getConnection().prepareStatement(sql);
    }

    // Tạo PreparedStatement, cho phép lấy về các key tự động sinh (primary key tự tăng)
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return DBHelper.getConnection().prepareStatement(sql, autoGeneratedKeys);
    }
}
