/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Server.Personal;

import java.awt.*;
import javax.swing.border.*;
import BUS.AccountBUS;
import BUS.ComputerUsageBUS;
import BUS.EmployeeBUS;
import BUS.InvoiceBUS;
import DTO.ComputerUsage;
import DTO.ComputerUsageFilter;
import DTO.Employee;
import GUI.Server.MainUI;
import Utils.ServiceProvider;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author Laffy
 */
public class PersonalSetting extends javax.swing.JPanel {
    private EmployeeBUS employeeService ;
    private ComputerUsageBUS computerUsageBUS;
    private AccountBUS accountBUS;
    private InvoiceBUS invoiceBUS;


    /**
     * Creates new form PersonalSetting
     */
    public PersonalSetting() {
        employeeService = ServiceProvider.getInstance().getService(EmployeeBUS.class);
        computerUsageBUS = ServiceProvider.getInstance().getService(ComputerUsageBUS.class);
accountBUS = ServiceProvider.getInstance().getService(AccountBUS.class);
        invoiceBUS = ServiceProvider.getInstance().getService(InvoiceBUS.class);
        initComponents();
        reDesign();

    }

    private void reDesign() {
        var employee = MainUI.getCurrentUser();
        try {
            var computerUsage = computerUsageBUS.findByFilter(
                    ComputerUsageFilter.builder().isEmployeeUsing(true).usedByAccountId(employee.getAccount().getId()).build());
            jTextFieldName.setText(employee.getName());
            jTextFieldUsername.setText(employee.getAccount().getUsername());
            jTextFieldSalary.setText(employee.getSalaryPerHour() + "");
            jTextFieldAddress.setText(employee.getAddress());
            jTextFieldPhoneNumber.setText(employee.getPhoneNumber());
            jTextAreaOther.setText(employee.getOtherInformation());
            var totalMoney = computerUsage.stream().mapToDouble(usage -> usage.getTotalMoney()).sum();
            var totalHour =0.0;
            for (var usage : computerUsage) {
                var minuteDiff = (usage.getEndAt().getTime() - usage.getCreatedAt().getTime()) / 1000 / 60;
                totalHour += minuteDiff*1.0 / 60;
            }
            var totalHourString = String.format("%.2f", totalHour);
            var totalMoneyString = String.format("%.2fđ", totalMoney);
            jTextFieldTotalTimeWork.setText(totalHourString);
            jTextFieldTotalSalary.setText(totalMoneyString);
            var currentMonth = java.time.LocalDate.now().getMonthValue();
            var currentYear = java.time.LocalDate.now().getYear();
            var currentMonthSalary = computerUsage.stream().filter(usage -> {
                var createdAt = usage.getCreatedAt();
                var month = createdAt.getMonth() + 1;
                var year = createdAt.getYear() + 1900;
                return month == currentMonth && year == currentYear;
            }).mapToDouble(ComputerUsage::getTotalMoney).sum();
            var currentMonthSalaryString = String.format("%.2fđ", currentMonthSalary);
            var currentMonthTimeWork = computerUsage.stream().filter(usage -> {
                var createdAt = usage.getCreatedAt();
                var month = createdAt.getMonth() + 1;
                var year = createdAt.getYear() + 1900;
                return month == currentMonth && year == currentYear;
            }).mapToDouble(usage -> {
                var minuteDiff = (usage.getEndAt().getTime() - usage.getCreatedAt().getTime()) / 1000 / 60;
                return minuteDiff*1.0 / 60;
            }).sum();
            var currentMonthTimeWorkString = String.format("%.2f", currentMonthTimeWork);
            jTextFieldSalaryInMonth.setText(currentMonthSalaryString);
            jTextFieldTimeInMonth.setText(currentMonthTimeWorkString);
            jTextFieldInvoice.setText(invoiceBUS.countExportInvoiceSellByEmployeeId(employee.getId()) + "");

        } catch (Exception e) {
            throw new RuntimeException(e);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jPanel5 = new JPanel();
        jLabel2 = new JLabel();
        jTextFieldName = new JTextField();
        jPanel6 = new JPanel();
        jLabel3 = new JLabel();
        jTextFieldUsername = new JTextField();
        jPanel7 = new JPanel();
        jLabel4 = new JLabel();
        jTextFieldSalary = new JTextField();
        jPanel8 = new JPanel();
        jLabel5 = new JLabel();
        jTextFieldAddress = new JTextField();
        jPanel9 = new JPanel();
        jLabel6 = new JLabel();
        jTextFieldPhoneNumber = new JTextField();
        jPanel10 = new JPanel();
        jLabel7 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextAreaOther = new JTextArea();
        jPanel16 = new JPanel();
        jButtonChangePass = new JButton();
        jButtonReset = new JButton();
        jButtonSave = new JButton();
        jPanel3 = new JPanel();
        jPanel11 = new JPanel();
        jLabel8 = new JLabel();
        jTextFieldTotalTimeWork = new JTextField();
        jPanel12 = new JPanel();
        jLabel9 = new JLabel();
        jTextFieldTotalSalary = new JTextField();
        jPanel13 = new JPanel();
        jLabel10 = new JLabel();
        jTextFieldTimeInMonth = new JTextField();
        jPanel14 = new JPanel();
        jLabel11 = new JLabel();
        jTextFieldSalaryInMonth = new JTextField();
        jPanel15 = new JPanel();
        jLabel12 = new JLabel();
        jTextFieldInvoice = new JTextField();
        jPanel4 = new JPanel();
        jLabel1 = new JLabel();

        //======== this ========
        setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax
        . swing. border .EmptyBorder ( 0, 0 ,0 , 0) ,  "JF\u006frmDes\u0069gner \u0045valua\u0074ion" , javax. swing
        .border . TitledBorder. CENTER ,javax . swing. border .TitledBorder . BOTTOM, new java. awt .
        Font ( "D\u0069alog", java .awt . Font. BOLD ,12 ) ,java . awt. Color .red
        ) , getBorder () ) );  addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override
        public void propertyChange (java . beans. PropertyChangeEvent e) { if( "\u0062order" .equals ( e. getPropertyName (
        ) ) )throw new RuntimeException( ) ;} } );
        setLayout(new BorderLayout());

        //======== jPanel1 ========
        {
            jPanel1.setBorder(new EmptyBorder(20, 20, 20, 20));
            jPanel1.setLayout(new GridLayout(1, 2, 20, 0));

            //======== jPanel2 ========
            {
                jPanel2.setBorder(new CompoundBorder(
                    new TitledBorder("Ch\u1ec9nh s\u1eeda th\u00f4ng tin"),
                    new EmptyBorder(20, 20, 20, 20)));
                jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

                //======== jPanel5 ========
                {
                    jPanel5.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel5.setOpaque(false);
                    jPanel5.setLayout(new BorderLayout());

                    //---- jLabel2 ----
                    jLabel2.setText("H\u1ecd v\u00e0 t\u00ean: ");
                    jPanel5.add(jLabel2, BorderLayout.NORTH);

                    //---- jTextFieldName ----
                    jTextFieldName.setText("jTextField1");
                    jPanel5.add(jTextFieldName, BorderLayout.CENTER);
                }
                jPanel2.add(jPanel5);

                //======== jPanel6 ========
                {
                    jPanel6.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel6.setOpaque(false);
                    jPanel6.setLayout(new BorderLayout());

                    //---- jLabel3 ----
                    jLabel3.setText("T\u00ean t\u00e0i kho\u1ea3n:");
                    jPanel6.add(jLabel3, BorderLayout.NORTH);

                    //---- jTextFieldUsername ----
                    jTextFieldUsername.setEditable(false);
                    jTextFieldUsername.setText("jTextField1");
                    jTextFieldUsername.setFocusable(false);
                    jTextFieldUsername.addActionListener(e -> jTextFieldUsernameActionPerformed(e));
                    jPanel6.add(jTextFieldUsername, BorderLayout.CENTER);
                }
                jPanel2.add(jPanel6);

                //======== jPanel7 ========
                {
                    jPanel7.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel7.setOpaque(false);
                    jPanel7.setLayout(new BorderLayout());

                    //---- jLabel4 ----
                    jLabel4.setText("L\u01b0\u01a1ng tr\u00ean gi\u1edd:");
                    jPanel7.add(jLabel4, BorderLayout.NORTH);

                    //---- jTextFieldSalary ----
                    jTextFieldSalary.setEditable(false);
                    jTextFieldSalary.setText("jTextField1");
                    jTextFieldSalary.setFocusable(false);
                    jTextFieldSalary.addActionListener(e -> jTextFieldSalaryActionPerformed(e));
                    jPanel7.add(jTextFieldSalary, BorderLayout.CENTER);
                }
                jPanel2.add(jPanel7);

                //======== jPanel8 ========
                {
                    jPanel8.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel8.setOpaque(false);
                    jPanel8.setLayout(new BorderLayout());

                    //---- jLabel5 ----
                    jLabel5.setText("\u0110\u1ecba ch\u1ec9 nh\u00e0: ");
                    jPanel8.add(jLabel5, BorderLayout.NORTH);

                    //---- jTextFieldAddress ----
                    jTextFieldAddress.setText("jTextField1");
                    jPanel8.add(jTextFieldAddress, BorderLayout.CENTER);
                }
                jPanel2.add(jPanel8);

                //======== jPanel9 ========
                {
                    jPanel9.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel9.setOpaque(false);
                    jPanel9.setLayout(new BorderLayout());

                    //---- jLabel6 ----
                    jLabel6.setText("S\u1ed1 \u0111i\u1ec7n tho\u1ea1i li\u00ean l\u1ea1c:");
                    jPanel9.add(jLabel6, BorderLayout.NORTH);

                    //---- jTextFieldPhoneNumber ----
                    jTextFieldPhoneNumber.setText("jTextField1");
                    jTextFieldPhoneNumber.addActionListener(e -> jTextFieldPhoneNumberActionPerformed(e));
                    jPanel9.add(jTextFieldPhoneNumber, BorderLayout.CENTER);
                }
                jPanel2.add(jPanel9);

                //======== jPanel10 ========
                {
                    jPanel10.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel10.setLayout(new BorderLayout());

                    //---- jLabel7 ----
                    jLabel7.setText("Kh\u00e1c:");
                    jPanel10.add(jLabel7, BorderLayout.NORTH);

                    //======== jScrollPane1 ========
                    {

                        //---- jTextAreaOther ----
                        jTextAreaOther.setColumns(30);
                        jTextAreaOther.setRows(5);
                        jScrollPane1.setViewportView(jTextAreaOther);
                    }
                    jPanel10.add(jScrollPane1, BorderLayout.CENTER);
                }
                jPanel2.add(jPanel10);

                //======== jPanel16 ========
                {
                    jPanel16.setBorder(new EmptyBorder(0, 1, 10, 1));
                    jPanel16.setLayout(new FlowLayout(FlowLayout.RIGHT));

                    //---- jButtonChangePass ----
                    jButtonChangePass.setText("\u0110\u1ed5i m\u1eadt kh\u1ea9u");
                    jButtonChangePass.addActionListener(e -> jButtonChangePassActionPerformed(e));
                    jPanel16.add(jButtonChangePass);

                    //---- jButtonReset ----
                    jButtonReset.setText("Reset");
                    jButtonReset.addActionListener(e -> jButtonResetActionPerformed(e));
                    jPanel16.add(jButtonReset);

                    //---- jButtonSave ----
                    jButtonSave.setText("L\u01b0u");
                    jButtonSave.addActionListener(e -> jButtonSaveActionPerformed(e));
                    jPanel16.add(jButtonSave);
                }
                jPanel2.add(jPanel16);
            }
            jPanel1.add(jPanel2);

            //======== jPanel3 ========
            {
                jPanel3.setBorder(new CompoundBorder(
                    new TitledBorder("Th\u1ed1ng k\u00ea chung"),
                    new EmptyBorder(20, 20, 20, 20)));
                jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));

                //======== jPanel11 ========
                {
                    jPanel11.setBorder(new EmptyBorder(1, 1, 20, 1));
                    jPanel11.setLayout(new BoxLayout(jPanel11, BoxLayout.X_AXIS));

                    //---- jLabel8 ----
                    jLabel8.setText("T\u1ed5ng s\u1ed1 gi\u1edd l\u00e0m: ");
                    jLabel8.setBorder(new EmptyBorder(1, 1, 1, 20));
                    jPanel11.add(jLabel8);

                    //---- jTextFieldTotalTimeWork ----
                    jTextFieldTotalTimeWork.setEditable(false);
                    jTextFieldTotalTimeWork.setText("jTextField1");
                    jTextFieldTotalTimeWork.setFocusable(false);
                    jPanel11.add(jTextFieldTotalTimeWork);
                }
                jPanel3.add(jPanel11);

                //======== jPanel12 ========
                {
                    jPanel12.setBorder(new EmptyBorder(1, 1, 20, 1));
                    jPanel12.setLayout(new BoxLayout(jPanel12, BoxLayout.X_AXIS));

                    //---- jLabel9 ----
                    jLabel9.setText("T\u1ed5ng ti\u1ec1n nh\u1eadn:");
                    jLabel9.setBorder(new EmptyBorder(1, 1, 1, 20));
                    jPanel12.add(jLabel9);

                    //---- jTextFieldTotalSalary ----
                    jTextFieldTotalSalary.setEditable(false);
                    jTextFieldTotalSalary.setText("jTextField1");
                    jTextFieldTotalSalary.setFocusable(false);
                    jPanel12.add(jTextFieldTotalSalary);
                }
                jPanel3.add(jPanel12);

                //======== jPanel13 ========
                {
                    jPanel13.setBorder(new EmptyBorder(1, 1, 20, 1));
                    jPanel13.setLayout(new BoxLayout(jPanel13, BoxLayout.X_AXIS));

                    //---- jLabel10 ----
                    jLabel10.setText("S\u1ed1 gi\u1edd l\u00e0m th\u00e1ng n\u00e0y:");
                    jLabel10.setBorder(new EmptyBorder(1, 1, 1, 20));
                    jPanel13.add(jLabel10);

                    //---- jTextFieldTimeInMonth ----
                    jTextFieldTimeInMonth.setEditable(false);
                    jTextFieldTimeInMonth.setText("jTextField1");
                    jTextFieldTimeInMonth.setFocusable(false);
                    jTextFieldTimeInMonth.addActionListener(e -> jTextFieldTimeInMonthActionPerformed(e));
                    jPanel13.add(jTextFieldTimeInMonth);
                }
                jPanel3.add(jPanel13);

                //======== jPanel14 ========
                {
                    jPanel14.setBorder(new EmptyBorder(1, 1, 20, 1));
                    jPanel14.setLayout(new BoxLayout(jPanel14, BoxLayout.X_AXIS));

                    //---- jLabel11 ----
                    jLabel11.setText("S\u1ed1 ti\u1ec1n l\u01b0\u01a1ng th\u00e1ng n\u00e0y:");
                    jLabel11.setBorder(new EmptyBorder(1, 1, 1, 20));
                    jPanel14.add(jLabel11);

                    //---- jTextFieldSalaryInMonth ----
                    jTextFieldSalaryInMonth.setEditable(false);
                    jTextFieldSalaryInMonth.setText("jTextField1");
                    jTextFieldSalaryInMonth.setFocusable(false);
                    jTextFieldSalaryInMonth.addActionListener(e -> jTextFieldSalaryInMonthActionPerformed(e));
                    jPanel14.add(jTextFieldSalaryInMonth);
                }
                jPanel3.add(jPanel14);

                //======== jPanel15 ========
                {
                    jPanel15.setBorder(new EmptyBorder(1, 1, 20, 1));
                    jPanel15.setLayout(new BoxLayout(jPanel15, BoxLayout.X_AXIS));

                    //---- jLabel12 ----
                    jLabel12.setText("S\u1ed1 \u0111\u01a1n \u0111\u00e3 b\u00e1n:");
                    jLabel12.setBorder(new EmptyBorder(1, 1, 1, 20));
                    jPanel15.add(jLabel12);

                    //---- jTextFieldInvoice ----
                    jTextFieldInvoice.setEditable(false);
                    jTextFieldInvoice.setText("jTextField1");
                    jTextFieldInvoice.setFocusable(false);
                    jTextFieldInvoice.addActionListener(e -> jTextFieldInvoiceActionPerformed(e));
                    jPanel15.add(jTextFieldInvoice);
                }
                jPanel3.add(jPanel15);
            }
            jPanel1.add(jPanel3);
        }
        add(jPanel1, BorderLayout.CENTER);

        //======== jPanel4 ========
        {
            jPanel4.setLayout(new FlowLayout());

            //---- jLabel1 ----
            jLabel1.setText("Th\u00f4ng tin ng\u01b0\u1eddi d\u00f9ng");
            jPanel4.add(jLabel1);
        }
        add(jPanel4, BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaryActionPerformed

    private void jTextFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumberActionPerformed

    private void jTextFieldTimeInMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeInMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeInMonthActionPerformed

    private void jTextFieldSalaryInMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaryInMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaryInMonthActionPerformed

    private void jTextFieldInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInvoiceActionPerformed

    private void jButtonChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePassActionPerformed
       var oldPass= JOptionPane.showInputDialog(this, "Nhập mật khẩu cũ", "Đổi mật khẩu", JOptionPane.INFORMATION_MESSAGE);
       if(MainUI.getCurrentUser().getAccount().getPassword().equals(oldPass)){
              var newPass= JOptionPane.showInputDialog(this, "Nhập mật khẩu mới", "Đổi mật khẩu", JOptionPane.INFORMATION_MESSAGE);
                if(newPass.isBlank()){
                    JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống", "Đổi mật khẩu", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
              MainUI.getCurrentUser().getAccount().setPassword(newPass);
           try {
               accountBUS.update( MainUI.getCurrentUser().getAccount());
               JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công", "Đổi mật khẩu", JOptionPane.INFORMATION_MESSAGE);
           } catch (SQLException e) {
               throw new RuntimeException(e);
           }
       }else {
              JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng", "Đổi mật khẩu", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_jButtonChangePassActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldName.setText(MainUI.getCurrentUser().getName());
        jTextFieldUsername.setText(MainUI.getCurrentUser().getAccount().getUsername());
        jTextFieldPhoneNumber.setText(MainUI.getCurrentUser().getPhoneNumber());
        jTextFieldAddress.setText(MainUI.getCurrentUser().getAddress());
        jTextAreaOther.setText(MainUI.getCurrentUser().getOtherInformation());
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        if(jTextFieldName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        }
        if(jTextFieldPhoneNumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        }
        if(jTextFieldAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        }
        var newEm = new Employee(MainUI.getCurrentUser());
        newEm.setName(jTextFieldName.getText());
        newEm.setPhoneNumber(jTextFieldPhoneNumber.getText());
        newEm.setAddress(jTextFieldAddress.getText());
        newEm.setOtherInformation(jTextAreaOther.getText());
        try {
            employeeService.updateEmployee(newEm);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Cập nhật", JOptionPane.INFORMATION_MESSAGE);
            MainUI.setCurrentUser(newEm);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel5;
    private JLabel jLabel2;
    private JTextField jTextFieldName;
    private JPanel jPanel6;
    private JLabel jLabel3;
    private JTextField jTextFieldUsername;
    private JPanel jPanel7;
    private JLabel jLabel4;
    private JTextField jTextFieldSalary;
    private JPanel jPanel8;
    private JLabel jLabel5;
    private JTextField jTextFieldAddress;
    private JPanel jPanel9;
    private JLabel jLabel6;
    private JTextField jTextFieldPhoneNumber;
    private JPanel jPanel10;
    private JLabel jLabel7;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaOther;
    private JPanel jPanel16;
    private JButton jButtonChangePass;
    private JButton jButtonReset;
    private JButton jButtonSave;
    private JPanel jPanel3;
    private JPanel jPanel11;
    private JLabel jLabel8;
    private JTextField jTextFieldTotalTimeWork;
    private JPanel jPanel12;
    private JLabel jLabel9;
    private JTextField jTextFieldTotalSalary;
    private JPanel jPanel13;
    private JLabel jLabel10;
    private JTextField jTextFieldTimeInMonth;
    private JPanel jPanel14;
    private JLabel jLabel11;
    private JTextField jTextFieldSalaryInMonth;
    private JPanel jPanel15;
    private JLabel jLabel12;
    private JTextField jTextFieldInvoice;
    private JPanel jPanel4;
    private JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
